### PR TITLE
#243 When renaming an object, fill in current name

### PR DESCRIPTION
**Pull request by sayyidhussain**
updated current name while renaming game object issue #243

### CODE REVIEW

**Comment by sayyidhussain** [comment]
https://github.com/JamesTKhan/Mundus/assets/85566851/eb5113dc-8870-4353-93c1-b72379bd1d34

**Review by JamesTKhan — APPROVED** [review]
Good catch I did not even know about this bug!

**Comment by sayyidhussain** [comment]
I have also done the change to populate the GameObject's current name into the TextField can i push it here or create a new pull request

**Comment by JamesTKhan** [comment]
> I have also done the change to populate the GameObject's current name into the TextField (as shown above) can i push it here or create a new pull request

Awesome, go ahead and push it to this PR

**Comment by sayyidhussain** [comment]
Sample Image of GameObject's current name populated into the TextField
image

**Comment by JamesTKhan** [comment]
Looks good, thanks!

**Pull request merged**
