### PR TITLE
Add boolean active to Skybox class in commons.

### PR DESCRIPTION
**Pull request by antzGames**
This PR is for someone using the Mundus runtime, who does not want to render a skybox, or wants to disable/enable skybox rendering whenever they want in their game.

edit: to disable/enable skybox rendering in the scene when ever they want.

### CODE REVIEW

**Comment by Dgzt** [comment]
If you move this variable into `Skybox` class like this:
```java
public boolean visible = true;
```

And move the render logic also into `Skybox` class what use this logic then you can disable/enable skybox on a screen not just all screen. And later can create settings screen for it in Mundus editor.

**Comment by antzGames** [comment]
I am open to moving the boolean to to the Skybox class, but not convinced that we should move the skybox render logic to it also.

Given that the rendering of the skybox happens in the Scene class, and you can only render one scene at a time (and therefore only 1 skybox at a time), it doesn't make sense to change the original intent of having the render logic for the entire scene in the Scene class.

It is just an opinion, I will let JTK chime in on what he thinks is best.  For me, I just need this functionality for a project I am working on.

**Comment by JamesTKhan** [comment]
Here is my thoughts. Keep render logic in the Scene for now. If we did move rendering logic out of Scene this is not the PR to do it with. Skybox doesn't derive from GameObject but the way you disable GameObjects is via an boolean active variable. 

For consistency lets do the same thing for Skybox. Add `public boolean active;` to Skybox class then check if skybox is active in Scene.java when rendering it. This will make it easy to tap into via the UI settings later.

The Skybox is public in Scene so the runtime should be able to access scene.skybox.active variable. Will merge PR if you can make that change.

**Comment by antzGames** [comment]
`public boolean active;`

added to `Skybox.java` and 

`this.active = true; `

set in constructor.

In the future if you guys add a active/inactive checkbox in the editor, maybe we should change the Skybox's constructor() and set() methods in the Skybox class to allow you to pass this `active` boolean parameter to the methods.

Let me know if you would like me to make any other changes.

**Review by JamesTKhan — APPROVED** [review]
Looks good, thanks!

**Comment by antzGames** [comment]
Thanks for approving this PR.  Disabling the skybox sets us free.   Link below:

https://imgur.com/eBJNIyO

**Pull request merged**
