### PR TITLE
Helper lines

### PR DESCRIPTION
**Pull request by Dgzt**
I've created helper line option into editor.

It can be enabled in the `Debug render options` dialog:
image

Rectangle helper lines:
image

Hexagon helper lines:
image

If the user change the map with a tool it will affect the helper lines also.

### CODE REVIEW

**Comment by Dgzt** [comment]
I want to migrate my tiled based map into mundus based map and I think it is useful feature.

**Comment by Dgzt** [comment]
Renamed `HelperLineObject` to `HelperLineShape`. Maybe it is better name.

**Comment by Dgzt** [comment]
I've found that the not full hexagons not visible correctly at end of map. I've fixed it.

Before fix:
image

After fix:
image

**Comment by JamesTKhan** [comment]
Looks like you put alot into this one, it looks neat in the editor. How do you use this for your game though? Just as a visual aid to help place items on the terrain? Just trying to understand its function.

Side note: I do not see the wireframe shader any more when clicking on the terrain on this branch. Does this replace that?

**Comment by antzGames** [comment]
Sorry for the late input, but would it be a lot of work to draw the NORMAL vector for both rectangle and hex modes? 

The normal vector can get retrieved from the existing getNormalAtWordCoordinate() in the Terrain class.  It is just a matter of drawing it.  If it is too late I can wait till the PR is merged and then add it later.

**Comment by Dgzt** [comment]
> Sorry for the late input, but would it be a lot of work to draw the NORMAL vector for both rectangle and hex modes?
> 
> The normal vector can get retrieved from the existing getNormalAtWordCoordinate() in the Terrain class. It is just a matter of drawing it. If it is too late I can wait till the PR is merged and then add it later.

Sorry, but it is not clear for me how can I use normal vectors in this case when the width can be 2 or more.

**Comment by antzGames** [comment]
So usually the normal is drawn at the center of the cube/rectangle/triangle of the terrain mesh.  Ignore this request as I can try to implement after this PR is merged.

image

**Pull request merged**
