### PR TITLE
Render events

### PR DESCRIPTION
**Pull request by Dgzt**
Hi,

I added render event handling. I want to render the part of building in dept capturing but render the whole building in the other render process. I've tried to figure out a generic solution for it.

https://user-images.githubusercontent.com/1684274/217779302-dcf26116-ebdd-4480-afd9-1c2a31f186d0.mp4

Example code:

```java
...

public class LibgdxMundusBuilding extends ApplicationAdapter {
	private ModelBatch batch;
	private Mundus mundus;
	private Scene scene;
	private TopDownCameraController controller;
	private BlendingAttribute blendingAttribute;
	private boolean show = true;
	
	@Override
	public void create () {
		...

		scene.sceneGraph.getRoot().getChildren().get(1).getComponents();
		for (final GameObject child : scene.sceneGraph.getRoot().getChildren()) {
			if (child.name.equals("house.gltf")) {
				final ModelComponent modelComponent = (ModelComponent) child.getComponents().get(0);

				blendingAttribute = new BlendingAttribute();

				final Material material = modelComponent.getModelInstance().getMaterial("Material.002");
				material.set(blendingAttribute);

				modelComponent.addEvent(new BeforeRenderEvent() {
					@Override
					public void action() {
						if (!show) {
							blendingAttribute.opacity = 0.0f;
						}
					}
				});

				modelComponent.addEvent(new AfterRenderEvent() {
					@Override
					public void action() {
						scene.batch.end();
						scene.batch.begin(scene.cam);
						blendingAttribute.opacity = 1.0f;
					}
				});

			}
		}
	}

	@Override
	public void render () {
		...

		if (Gdx.input.isKeyJustPressed(Input.Keys.R)) {
			show = !show;
		}

                ...
	}
	
	...
```

Example project:
[libgdx-mundus-building.zip](https://github.com/JamesTKhan/Mundus/files/10714787/libgdx-mundus-building.zip)

### CODE REVIEW

**Comment by Dgzt** [comment]
This won't work with object what use model cache. A trick is needed here.

**Comment by Dgzt** [comment]
I implemented this feature for ModelCacheManager too. I updated the example code and reuploaded the example project.

**Comment by JamesTKhan** [comment]
This looks interesting I will test it out soon

**Comment by JamesTKhan** [comment]
Checked out the demo and code. I am open to merging it, not sure how many actual use cases it has but I do not see any harm in having custom events for before or after a render. 

In your example code though I think it wouldn't scale well if you had lots of houses because every post event is flushing the batch.

Any reason to not put all the render event logic in to AbstractComponent instead of CullableComponent?

**Comment by Dgzt** [comment]
> Checked out the demo and code. I am open to merging it, not sure how many actual use cases it has but I do not see any harm in having custom events for before or after a render.
> 
> In your example code though I think it wouldn't scale well if you had lots of houses because every post event is flushing the batch.

Yes, I'm sure that this is not the best solution, but currently I don't know better solution to render whole model in dept rendering and render part of model in other rendering.

>     1. Any reason to not put all the render event logic in to AbstractComponent instead of CullableComponent?

The `LightComponent` also extends `AbstractComponent` what has not a valid render method where can trigger events, so I implemented it in `CullableComponent`. 
 
>     2. Have you tested this on HTML yet just to make sure it all compiles? Otherwise I can probably test later today.

I've not tested this feature on HTML. Thanks if you test it. The weekend at the earliest when I can test it on HTML.

**Comment by JamesTKhan** [comment]
I may have a suggestion that will prevent having to flush the batch like that. Have a render event that is executed pre-render and a separate render event executed pre-depth render. That way, on the pre-depth render you would switch the opacity back to 1.0.

I just did a quick test and it works without flushing the batch.

Maybe have a RenderEventPass enum.. that is either RenderPass or DepthPass, etc... and that enum is passed with the triggerEvent so that you can check in your before and after render events which pass it is? Something like that. May not even need the after render event anymore? Just a BeforeRenderEvent and BeforeDepthRenderEvent?

Something like so
image

**Comment by Dgzt** [comment]
> I may have a suggestion that will prevent having to flush the batch like that. Have a render event that is executed pre-render and a separate render event executed pre-depth render. That way, on the pre-depth render you would switch the opacity back to 1.0.
> 
> I just did a quick test and it works without flushing the batch.
> 
> Something like picture below May not even need the after render event anymore? Just a BeforeRenderEvent and BeforeDepthRenderEvent?
> 
> Something like so image

Thanks, I've implemented it and works.

Here is the example code:

```
modelComponent.addEvent(new BeforeRenderEvent() {
	@Override
	public void action() {
		if (!show) {
			blendingAttribute.opacity = 0.0f;
		}
	}
});

modelComponent.addEvent(new BeforeDeptRenderEvent() {
	@Override
	public void action() {
		blendingAttribute.opacity = 1.0f;
	}
});
```

The testing on HTML is missing, maybe I can do it on the next days.

**Comment by Dgzt** [comment]
I've fixed the code for HTML. 

Here is the example project:
[libgdx-mundus-building-html.zip](https://github.com/JamesTKhan/Mundus/files/10801123/libgdx-mundus-building-html.zip)

**Comment by JamesTKhan** [comment]
Everything looks good, one last thing. Could you fix the spelling on "Dept" should be "Depth"

**Comment by Dgzt** [comment]
Done.

**Comment by JamesTKhan** [comment]
Thanks!

**Pull request merged**
