### PR TITLE
Updated libgdx to 1.11.0

### PR DESCRIPTION
**Pull request by Dgzt**

### CODE REVIEW

**Comment by jpooleycodes** [comment]
I have not merged yet as I am noticing some subtle micro-stutters on the demo app when running on this branch. Primarily in the "Second Scene". The FPS still shows 60fps but some stuttering is visible. I might have to experiment with it more after the upcoming game jam, there is no telling what the cause is.

**Comment by Dgzt** [comment]
I've updated this branch with the latest master branch. Could you check there are still some stuttering in the demo app?

**Comment by JamesTKhan** [comment]
@Dgzt Unfortunately I still see the micro-stuttering. The game stays at 60fps but I get jarring microstutters when moving the camera around on the example project. On master branch, its smooth. I made a short video to show what I am seeing. I am thinking it might be lwjgl or window related but I will have to dig into it more 

https://user-images.githubusercontent.com/28971753/185227850-1860aa55-5c3c-4c0c-9535-00887a8be9d8.mp4

**Comment by JamesTKhan** [comment]
Confirmed this is not a Mundus issue. Replicated same issue in a barebones test project. It seems to only happen on Windowed mode on 1.11.0. Raised the issue in discord but will update here when I know more.

**Comment by JamesTKhan** [comment]
After some talks in Discord, I tested on 1.10.0, and overrode the LWJGL version to 3.3.0 (1.10.0 uses 3.2.3) and replicated the stuttering so it seems to be a LWJGL (or GLFW) issue because LWJGL version was updated on 1.11.0. It only appears to happen in windowed mode. 

So I am not sure when we can merge this PR.

**Comment by Dgzt** [comment]
I see, I hope the lwjgl or glfw team will fix it soon.

**Comment by Dgzt** [comment]
There was new lwjgl version [(3.3.2)](https://github.com/LWJGL/lwjgl3/releases/tag/3.3.2) with updated glfw:. I hope this will resolve micro-stuttering issue.

**Comment by Dgzt** [comment]
> We can hope. I looked through the change lists for 3.3.2 and don't see it mentioned but who knows. Have you noticed the micro stuttering on your end at all? It is terrible for me on libGDX 1.11 when windowed mode.

No, I haven't. My eyes are not enough good or maybe it depends on OS and/or GPU type.

**Comment by JamesTKhan** [comment]
I will likely end up merging this sooner than later. We can't stay on 1.10 forever and no matter what I cannot seem to pinpoint the stuttering or find any mention of it on GLFW or LWJGL3 GitHub. Maybe this is just an issue on my end, difficult to say.

**Comment by Dgzt** [comment]
The [3.3.2 update](https://github.com/libgdx/libgdx/pull/7121) has merged into libGDX. Could you try with the latest libGDX snapshot?

**Comment by JamesTKhan** [comment]
> The [3.3.2 update](https://github.com/libgdx/libgdx/pull/7121) has merged into libGDX. Could you try with the latest libGDX snapshot?

The stuttering appears to be gone on 1.11.1-SNAPSHOT!

**Review by JamesTKhan — APPROVED** [review]
I can't even replicate the stuttering this morning on 1.11.0 or 1.11.1-Snapshot... 
Not sure what is happening but we can merge this now.

**Comment by Dgzt** [comment]
Strange. As I remember rafaskb also had this shuttering on his environment, not only your environment.

**Pull request merged**
