### PR TITLE
Terrain chunks LoD

### PR DESCRIPTION
**Pull request by freyinds**
This PR fixes a logic error which was incorrectly assigning left and right neighbors during terrain chunk generation. I think we should consider converting the coordinate system from left-handed to right.

### CODE REVIEW

**Comment by freyinds** [comment]
Closing this to try to get the LOD system working with the current terrain chunk generation code.

**Comment by freyinds** [comment]
oops almost ready

**Comment by freyinds** [comment]
Ready for review and feedback. Skirts extend edges and depth.

**Comment by freyinds** [comment]
Currently you need to re-load the project for the LOD levels to be created properly. I am trying to work my way through your multi-threaded chunk generation code so that it does not require a re-load but I have not been able to figure that out yet. Please try to reload the project and see what you think.

**Comment by JamesTKhan** [comment]
> Currently you need to re-load the project for the LOD levels to be created properly. I am trying to work my way through your multi-threaded chunk generation code so that it does not require a re-load but I have not been able to figure that out yet. Please try to reload the project and see what you think.

If you have questions on the thread stuff let me know, I wrote it and then DGZT cleaned it up a bit. But, you generate LoDs in the TerrainComponent update method right? Why does the threaded generation code need to be changed?

**Comment by freyinds** [comment]
Check latest PR. I am trying to add the ability to set number of LOD models and LOD draw distance into AddTerrainChunksDialog. I am having issues initializing terrain, terrainAsset and terrainComponent. I am busy with my normal job this week and maybe you guys can help me debug. Current issue is not having a Maerial assigned to the base model.

**Comment by freyinds** [comment]
Depreciated by new terrain chunking PR. There is some decent terrain neighbor code in here as well as some attempts at LOD picking by screen size raito.

**Pull request closed without merging**
